### ISSUE TITLE
Implement alternative CI provider(s)

### ISSUE THREAD

**Issue by janpio** [apache/cordova-paramedic#103]
AppVeyor and Travis both work, but are really slow (mostly queue time of Apache accounts). Although we can't use any other CI providers like Azure Pipelines or Circle CI on Apache repositories, having a working Ci configuration would still help to test forks and thus the content of PRs.

Example for an Azure Pipelines configuration:
https://github.com/apache/cordova-lib/pull/696/files

**Comment by erisu** [comment]
Closing out this ticket as we have implemented the GH Actions CI service.
