### ISSUE TITLE
CI: Also test Android locally

### ISSUE THREAD

**Issue by janpio** [apache/cordova-paramedic#134]
#131 reworked the `local` bit of the CI config so that we can run multiple local tests and supply the appropriate configuration for them.:

```
    - env: PLATFORM=local/android-5.1
      <<: *_android
```

Unfortunately the `target` values currently hardcoded in the Android configs (e.g. `"target": "api22",`) do not work on Travis:

```
cordova-paramedic: running tests locally
cordova-paramedic: Choosing Target for Android
cordova-paramedic: Target defined as: api22
cordova-paramedic: running command cordova run android --no-telemetry --no-update-notifier --target "api22"
...
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=/usr/local/android-sdk/ (DEPRECATED)
CordovaError: Promise rejected with non-error: 'Target \'api22\' not found, unable to run project'
    at cli.catch.err (/home/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova/bin/cordova:29:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Error: Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=/usr/local/android-sdk/ (DEPRECATED)
...
Completed tests at 5:09:27 PM
Collecting logs for the devices.
running:
    adb devices
$ adb devices
List of devices attached
Error: There must be exactly one emulator/device attached
Uninstalling the app.
cordova-paramedic: Running command: adb -s api22 uninstall io.cordova.hellocordova
$ adb -s api22 uninstall io.cordova.hellocordova
error: device 'api22' not found
- waiting for device -
cordova-paramedic: App uninstall timed out!
...
The command "if [[ "$PLATFORM" =~ local ]]; then node main.js --config ./pr/$PLATFORM --plugin ./spec/testable-plugin/ --buildName travis-paramedic-$TRAVIS_JOB_NUMBER; fi" exited with 1.
```

I also fear that emulators in general don't work yet, as there is additional work required to get those function:

> If you feel adventurous, you may use the script /usr/local/bin/android-wait-for-emulator and adapt your .travis.yml to make this emulator available for your tests.

https://docs.travis-ci.com/user/languages/android/#how-to-create-and-start-an-emulator

**Comment by janpio** [comment]
SauceLabs removed their Android 4.4 emulators. 
As Cordova Android 8.x still supports 4.4 (and is used by >7% of Android users) we have to find other solutions to test that version. Being able to test locally on an Android emulator on Travis would be nice.

**Comment by erisu** [comment]
1. add system image to components
```
  android:
    components:
      - tools
      - build-tools-$ANDROID_BUILD_TOOLS_VERSION
      - android-$ANDROID_API_LEVEL
      - sys-img-x86-android-$ANDROID_API_LEVEL
```

2. create the emulator
```
- |
    if [[ "$PLATFORM" =~ android ]]; then
        echo no | android create avd --force -n api28 -t "android-28" -b "default/x86";
        emulator -avd api28 -no-audio -no-window &
        android-wait-for-emulator
    fi
```

`-n` = the emulator name.. n the  example above the emulator name is api28. I installed and used 28 for everything as we had this defined above.
```
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
```

**Comment by erisu** [comment]
I am closing out this ticket as we have moved to GH Actions which runs local teting (emulators on the GH Actions instance).

We dropped the past CI setup, TravisCI  + SauseLabs because it was only testing against emulators and not physical device. This same test covereage was achievable with only GH Actions.
