### ISSUE TITLE
Handle SauceLabs on forks of repos

### ISSUE THREAD

**Issue by janpio** [apache/cordova-paramedic#135]
When someone forks this or one of the plugins repos using this, SauceLabs will not work as the jwt secure variable containing the sauce labs key will not be valid for that repo.

We could try to find a way to a) not fail in those scenarios or b) offer a workaround somehow, so that users can at least easily provider their own key.

**Comment by timbru31** [comment]
Just dropping a random note: JWT addon is deprecated since >1 year on TravisCI (https://blog.travis-ci.com/2018-01-23-jwt-addon-is-deprecated).

Basically it could stop working any given day?

**Comment by janpio** [comment]
Known issue, but obv. not written down anywhere, so I created: https://github.com/apache/cordova-paramedic/issues/136

**Comment by timbru31** [comment]
> b) offer a workaround somehow

SauceLabs needs an API key - so I doubt this is impossible without exposing the key to everyone :(

**Comment by janpio** [comment]
If travis.yml could read from a file, we could have a gitignored file or via ENV var for some environments. Maybe Travis allows overwriting those values via a repo specific ENV var? Something like this.

**Comment by timbru31** [comment]
> we could have a gitignored file

Since TravisCI clones the repo, how should this work?

> ENV var for some environments

Define "some environments". Everything from outside the Apache org can read every ENV var, that's the problem :(

**Comment by janpio** [comment]
If everyone else _besides_ Apache could use ENV vars to overwrite the JWT stuff, this could work. In my testing some time ago this unfortunately was not the case - the JWT var overwrote ENV vars. But we should retest that.

**Comment by erisu** [comment]
Closing out ticket since we are removing Travis CI and AppVeyor. SauceLabs & its JWT token will no longer be used.
