### ISSUE TITLE
Travis: JWT addon is deprecated

### ISSUE THREAD

**Issue by janpio** [apache/cordova-paramedic#136]
JWT addon is used to secure the Sauce Labs key in our travis.yml:

> Just dropping a random note: JWT addon is deprecated since >1 year on TravisCI (blog.travis-ci.com/2018-01-23-jwt-addon-is-deprecated).
>
> Basically it could stop working any given day?
(Quote: At the scheduled date of April 17, 2018, the addon will cease to function. )
> 
> https://github.com/apache/cordova-paramedic/issues/135#issuecomment-490043884

April 17, 2018 came and went and nothing happened yet. The JWT plugin is also still mentioned in the Travis docs today.

So I think this is mixed message and we are happy to use it until it stops working, as there is no real working replacement available.

**Comment by timbru31** [comment]
We can ditch the JWT addon :) - for each repo we can just configure the env variables SAUCE_ACCESS_KEY and SAUCE_USERNAME (I assume some config changes would be needed to read from the environment variables) and *do not* output them. The problem of #135 remains of course.

See attached, image, too:
<img width="1059" alt="Screen Shot 2019-05-12 at 22 27 15" src="https://user-images.githubusercontent.com/838003/57587457-4d14b600-7505-11e9-8dda-497d08b4e9c6.png">

**Comment by timbru31** [comment]
I have to adjust my comment a bit. Forks do have access to these variables, but they are filtered from the log file of Travis (see https://docs.travis-ci.com/user/best-practices-security/#Steps-Travis-CI-takes-to-secure-your-data) but an attacker might be able to "send" them anywhere.

**Comment by janpio** [comment]
... which is exactly why the JWT addon exists - there is is a bit harder to get the values ;)

Meh, you gave me hope for a minute here :D

**Comment by timbru31** [comment]
Next try: The proper method is to use the Travis encryption add-on to securely inject the password/token: https://docs.travis-ci.com/user/encryption-keys/

**Comment by janpio** [comment]
> Please note that encrypted environment variables are not available for pull requests from forks.

This means that PRs from forks could not run their tests on SauceLabs, which is bad because we would only discover bugs after the PR has been merged as only then it would run tests.

**Comment by timbru31** [comment]
Yes the problem of #135 remains :(

**Comment by erisu** [comment]
I am closing out this ticket as we are moving away from TravisCI & AppVeyor. The JWT token will not be being used in GH Actions.

All plugins are now configured with GH Actions as its main CI and shortly the TravisCI and AppVeyor configs are going to be removed.
