### ISSUE TITLE
Local Appium: `npm install appium` requires Node >= 8

### ISSUE THREAD

**Issue by janpio** [apache/cordova-paramedic#157]
local appium server install:

https://github.com/apache/cordova-paramedic/blob/a9f377b4a2fef4fa74c50446850795b67ec0b92b/lib/appium/AppiumRunner.js#L411-L414

+

https://github.com/appium/appium/blob/dba3a87c54b0507bd40fc9dba759949978381ce3/package.json#L24-L25:

```
  "engines": {
"node": ">=8",
```

**Comment by breautek** [comment]
Closing as obsolete
