### ISSUE TITLE
Add new test for AndroidX support

### ISSUE THREAD

**Issue by janpio** [apache/cordova-paramedic#189]
https://github.com/apache/cordova-plugin-camera/pull/418 gave me the idea, that it would probably be nice to test AndroidX compatibility of our plugins automatically. Paramedic seems to be the obvious choice.

Implementation would be pretty simple, just install `cordova-plugin-androidx` like @davidschreiber suggested in https://github.com/apache/cordova-plugin-camera/pull/418#issuecomment-508519820

Probably no reason to duplicate all Android jobs, one job should be enough to verify if it also works with AndroidX support enabled. I suggest we use one of the newer Android versions, and just add a new flag to install the plugin. Then we can add that new "environment" to our CI configuration where appropriate (which also enables us to create PRs adding this to all plugins, and not merge those that cause this test to fail until AndroidX support is fixed).

`cordova-plugin-camera` would be an obvious test subject, as the AndroidX support is already waiting to be merged in https://github.com/apache/cordova-plugin-camera/pull/418 - just have to be faster here as that PR is getting merged.

**Comment by janpio** [comment]
First naive implementation is in #190, not sure if this is the right way to actually do this.

**Comment by erisu** [comment]
Closing out this ticket as AndroidX was already integrated in Cordova-Android 10.x and being tested.
