### ISSUE TITLE
Improve error output: "(node:12608) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead."

### ISSUE THREAD

**Issue by janpio** [apache/cordova-paramedic#196]
When I use current `master` locally (via `npm link`) I get this output:

```
λ cordova-paramedic --platform android --plugin ./ --target 02e7f7e9215da7f8
cordova-paramedic: Will use the following cli: cordova
(node:12608) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
```

Can we improve this error output somehow so it is clearer where this is used? It doesn'T seem to be in paramedic itself, but I have no idea how to dig deeper.

**Comment by raphinesse** [comment]
I _think_ this has been fixed by the `tmp` update in https://github.com/apache/cordova-paramedic/commit/c9813c430676f5079b1600f193a85f9df7b78e9e
