### ISSUE TITLE
npm package cordova-paramedic is published from other repo

### ISSUE THREAD

**Issue by janpio** [apache/cordova-paramedic#28]
https://www.npmjs.com/package/cordova-paramedic is published from https://github.com/purplecabbage/cordova-paramedic, not this repository.

**Comment by timbru31** [comment]
Any idea how this could be resolved? I've noticed this issue since some CI configs of plugins are installing cordova-paramedic from git rather than npm. @purplecabbage would you be open to "donate" the name back to this repo?

**Comment by purplecabbage** [comment]
Done.
Start a vote thread if you want to release it.
