### ISSUE TITLE
no releases

### ISSUE THREAD

**Issue by janpio** [apache/cordova-paramedic#29]
although there are versions published to npm ([although from a different repo](https://github.com/apache/cordova-paramedic/issues/28)) there are no releases available here, so no idea what these published versions belong to.

**Comment by janpio** [comment]
I created a `0.5.0` tag/release that should match what is currently available on npm: https://www.npmjs.com/package/cordova-paramedic/v/0.5.0

**Comment by Mykaelos** [comment]
Hey @janpio, do you know if/when the npm version of cordova-paramedic will be updated from this repo?

There seem to be differences between the apache/cordova-paramedic#0.5.0 tag and the purplecabbage/cordova-paramedic#0.5.0 tag. The big one being that the apache version has the new --args flag which is needed to use the old iOS build system (and for the tests to run at all in a Xcode 10+ environment).

I worked around it by pointing npm at this repo, but I prefer to use npm's artifacts, and this might end up being a trap for others (probably similar to https://github.com/apache/cordova-paramedic/issues/95).

**Comment by janpio** [comment]
Not really. 

Someone would have to or should review all the code changes between 0.5.0 and now again and confirm that we didn't break anything or that any documentation is missing.

On the other hand, the current state is used in production for the Cordova plugin repos anyway.
