### ISSUE TITLE
'rm' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by janpio** [apache/cordova-paramedic#66]
Originally reported by @dopry at https://issues.apache.org/jira/browse/CB-14208

When running any cordova paramedic command I get the error message

'rm' is not recognized as an internal or external command,
operable program or batch file.
result code is : 1

**Comment by janpio** [comment]
paramedic seems to use `shell.rm` in several places: https://github.com/apache/cordova-paramedic/search?q=rm&unscoped_q=rm Seems this is not cross platform save, so this doesn't work on Windows :/

Can you please provide more of the output you are getting so we can track this down?

**Comment by dopry** [comment]
Glad to see everything moving to GH. I don't have extra output and I'm not working on this project for the foreseeable future.   I do work on windows so that could be the issue. Is there an alternative to shell.rm that is cross-platform friendly?

**Comment by janpio** [comment]
`shelljs` actually _is_ cross platform friendly, so there probably was something confusing paramedic or shelljs for you (I can run all non-iOS things with paramedic locally).

If you encounter this problem again, please do create a new issue with some additional output from the command so we have some context. Thanks!
