### ISSUE TITLE
Build fails with modern Xcode build system

### ISSUE THREAD

**Issue by NiklasMerz** [apache/cordova-paramedic#92]
My paramedic run fails because it uses the "modern build system" Like https://github.com/apache/cordova-ios/issues/407 suggested I would like to pass the `--buildFlag='-UseModernBuildSystem=0'` flag to run the build. 

Am I missing a paramedic CLI parameter or is this not possible? Should we introduce a way to pass the parameter or use `build.json` file?

```
Build settings from configuration file '/private/var/folders/9k/8k2t2pv92q363byqcvfw_1340000h8/T/tmp-10046izGkKwIVm54n/platforms/ios/cordova/build-debug.xcconfig':
    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES
    CODE_SIGN_ENTITLEMENTS = $(PROJECT_DIR)/$(PROJECT_NAME)/Entitlements-$(CONFIGURATION).plist
    CODE_SIGN_IDENTITY = iPhone Developer
    ENABLE_BITCODE = NO
    GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1
    HEADER_SEARCH_PATHS = "$(TARGET_BUILD_DIR)/usr/local/lib/include" "$(OBJROOT)/UninstalledProducts/include" "$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include" "$(BUILT_PRODUCTS_DIR)"
    OTHER_LDFLAGS = -ObjC
    SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h

/private/var/folders/9k/8k2t2pv92q363byqcvfw_1340000h8/T/tmp-10046izGkKwIVm54n/platforms/ios/build/emulator/HelloCordova.app/Info.plist file not found.
```

**Comment by janpio** [comment]
If you can't find a way to supply this to the `cordova build` command, this should definitely be added somehow.

**Comment by NiklasMerz** [comment]
I found the parameter `--args` which does what I needed for this situation thats why I created two PRs:

* Document the parameter for other users #94 
* Fix the npm test for the plugin itself with the Xcode flag. #93 

Are the documentation changes good? Should we explain the workaround more for other users or paramedic?
